// Draft-only preparation: never admission, transition or snapshot promotion.
import {writeFileSync} from 'node:fs';
import {canonical,digest,descriptor as checkDescriptor} from '@alica/acap-contracts';
import {validateDefinition,localReader} from '@alica/catalog';
import {validateProposal} from '@alica/catalog/governance';
const object=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const key={type:'string',minLength:1,maxLength:64},value={type:'string',maxLength:4096};
const descriptor={schemaVersion:'acap.capability/v1',id:'io.alica.example.records',version:'1.0.0',features:[],operations:[
 {name:'put',kind:'unary',idempotency:'none',input:object({key,value}),output:object({stored:{type:'boolean',const:true}})},
 {name:'get',kind:'unary',idempotency:'none',input:object({key}),output:object({found:{type:'boolean'},value})}
]};
const policy={apiVersion:'catalog.alica.io/namespace-v1',version:'1.0.0',namespaces:[{authority:'alica.io',domain:'example',kind:'first-party',owner:'ALICA maintainers'}],release:[]};
const definition={apiVersion:'catalog.alica.io/v1',kind:'CapabilityDefinition',metadata:{id:'acap://alica.io/example/records@1',version:'1.0.0',maturity:'proposed',owner:'ALICA maintainers',summary:'Bounded neutral text records with explicit absence and normal stop/start persistence.'},contract:{descriptor:'descriptor.json',identity:descriptor.id,version:descriptor.version,digest:digest(descriptor)},semantics:{description:'Put replaces one key; get returns found false and empty value only for observed absence, never failure. Maximum32 records. A completed put survives normal stop/start of the service with the same operator-owned data directory. No crash durability, transactions, backup, migration or hostile-code confinement guarantee. See SEMANTICS.md.',cancellation:'supported',errors:['INVALID_ARGUMENT','PERMISSION_DENIED','UNAVAILABLE','CANCELLED','DEADLINE_EXCEEDED','RESOURCE_EXHAUSTED']},scopes:['application','session'],permissions:['example.records'],dependencies:[],events:[]};
const proposal={apiVersion:'catalog.alica.io/proposal-v1',id:'phase50-example-records-v1',problem:'Phase5.0 requires a tiny stateful reference whose completed writes survive normal service stop/start and whose absence is not confused with failure.',existingInsufficient:'Echo is explicitly side-effect-free; agent execution and decision evaluation do not offer record persistence. Repurposing any frozen capability would violate its semantics.',abstraction:'Bounded opaque text key/value put/get with explicit found flag, fixed reference quota and normal restart persistence. No search, embeddings, backup, schema migration or product-specific memory API.',providers:['Native single-file reference resource (implemented, qualification pending)','Independent external-author file resource (planned; same contract and no product dependency)'],consumers:['Unchanged public SDK record consumer in service-foundation/reference/services.mjs'],draft:definition.metadata.id,alternatives:'Do not add stateful semantics to echo; no MemoryV4 dependency or generic storage engine; explicit native service-owned resource rather than modifying frozen Kernel.',security:'Existing Host grants enforce capability operations. Native resource ownership belongs to operator topology; no filesystem confinement claim. Permission metadata grants nothing; data never included in diagnostics.',scopes:'Application/session; operation grants put/get, neutral permission label example.records. No new grant or scope type.',compatibility:'New experimental proposal only; no original definitions/snapshots changed. Admission and separate snapshot require independent parent review and existing Catalog transition.',genericRationale:'Opaque bounded records demonstrate state ownership and persistence without encoding future products or implementation technology.',proposer:'Hermes Phase5.0 implementation worker'};
checkDescriptor(canonical(descriptor));validateProposal(proposal);
for(const [name,data] of Object.entries({'descriptor.json':descriptor,'definition.json':definition,'namespace-policy.json':policy,'proposal.json':proposal}))writeFileSync(new URL(name,import.meta.url),JSON.stringify(data,null,2)+'\n');
validateDefinition(definition,localReader(new URL('.',import.meta.url).pathname),policy,{release:false});
console.log(JSON.stringify({status:'PROPOSAL_VALIDATED_NOT_ADMITTED',descriptorDigest:digest(descriptor),releaseEntries:0}));
