// Draft preparation ONLY. Does not review, admit, transition, snapshot or publish.
import {writeFileSync} from 'node:fs';
import {canonical,digest,descriptor as checkDescriptor} from '@alica/acap-contracts';
import {validateDefinition,localReader} from '@alica/catalog';
import {validateProposal} from '@alica/catalog/governance';
const object=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const string=(maxLength,minLength=0)=>({type:'string',minLength,maxLength});
const scope=string(1000,1),id=string(200,1),title=string(240,1),content=string(8192,1);
const sources={type:'array',maxItems:8,items:string(512,1)};
const provenance=object({source:string(240,1)});
const candidate=object({id,scope,title,content,sourceRefs:sources,provenance,author:string(200,1),version:{type:'integer',minimum:1,maximum:2147483647},role:{type:'string',const:'active'},lifecycle:{type:'string',const:'working'}});
const descriptor={schemaVersion:'acap.capability/v1',id:'io.alica.memory.candidates',version:'1.0.0',features:[],operations:[
 {name:'create',kind:'unary',idempotency:'provider',idempotencyPolicy:{retentionMs:86400000,persistence:'durable'},input:object({scope,title,content,sourceRefs:sources,provenance}),output:candidate},
 {name:'get',kind:'unary',idempotency:'none',input:object({scope,id}),output:candidate},
 {name:'search',kind:'unary',idempotency:'none',input:object({scope,query:string(500,1),limit:{type:'integer',minimum:1,maximum:25},cursor:string(4096)}),output:object({candidates:{type:'array',maxItems:25,items:candidate},nextCursor:string(4096)})}
]};
const policy={apiVersion:'catalog.alica.io/namespace-v1',version:'1.0.0',namespaces:[{authority:'alica.io',domain:'memory',kind:'first-party',owner:'ALICA maintainers'}],release:[]};
const definition={apiVersion:'catalog.alica.io/v1',kind:'CapabilityDefinition',metadata:{id:'acap://alica.io/memory/candidates@1',version:'1.0.0',maturity:'proposed',owner:'ALICA maintainers',summary:'Scoped durable working candidates with attributable provenance, stable IDs and bounded lexical retrieval.'},contract:{descriptor:'descriptor.json',identity:descriptor.id,version:descriptor.version,digest:digest(descriptor)},semantics:{description:'Create active/working author-only candidates; get/search only visible active/working records representable without truncation. Stable IDs and completed creates survive normal restart. Mandatory durable actor-key idempotency for create, at least24h retention. Host operation grants plus independently narrowed data authority; no actor/promotion/import authority in payload. Search records retrieval evidence; absence/outage distinct. See SEMANTICS.md.',cancellation:'supported',errors:['INVALID_ARGUMENT','UNAUTHENTICATED','PERMISSION_DENIED','NOT_FOUND','CONFLICT','FAILED_PRECONDITION','UNAVAILABLE','RESOURCE_EXHAUSTED','CANCELLED','DEADLINE_EXCEEDED']},scopes:['application','session'],permissions:['memory.create-working','memory.read','memory.search'],dependencies:[],events:[]};
const proposal={apiVersion:'catalog.alica.io/proposal-v1',id:'phase51-memory-candidates-v1',problem:'An external project worker must create one scoped working note with attributable provenance, retrieve its stable ID, search it, stop/restart the provider, then retrieve it again without direct HTTP/database/framework coupling.',existingInsufficient:'Frozen echo is side-effect-free; example.records is opaque replaceable key/value without governed scope/provenance/candidate semantics or search. Agent-execution and decision-evaluate do not provide durable governed memory. Changing their semantics is prohibited.',abstraction:'Exactly one generic working-candidate capability with create/get/search, explicit scope as requested target not authority, stable opaque IDs, bounded text/source provenance. No broad memory family, HTTP dispatch, provider-specific table/schema names or promotion/export/admin operations.',providers:['Governed MemoryV4 shared-domain SQLite adapter (authorized planned implementation, not yet built)','Any independent governed candidate provider satisfying these public semantics; no requirement to implement one speculatively'],consumers:['External public-SDK project working-note consumer; create/get/search/restart/get with no MemoryV4, FastAPI or SQLite imports'],draft:definition.metadata.id,alternatives:'Rejected repurposing echo or generic records because existing contracts lack governance; rejected HTTP wrapping/store bypass and a generic memory API. Keep canonical exchange an explicit restricted operator task, outside this worker capability.',security:'Trusted Host OperationContext.caller supplies identity; operator mapping narrows to actor/data-root/permissions. Body contains no identity/grants. Domain reevaluates scope/create-working/read/search and audits writes/search. Source provenance is asserted content, not authentication. Working-only output cannot promote canonical truth. Deadlines/cancellation do not guarantee rollback; explicit same-key retry only.',scopes:'Existing application/session Catalog labels and Host scope/grants unchanged. Requested memory scope must equal/descend separately mapped data-root; visible ancestor candidates only; no public opt-in or sibling leakage. Catalog permission metadata grants nothing.',compatibility:'Additive new candidate descriptor/proposal only; original contracts/catalog snapshots/Foundation unchanged. Independent distinct-parent review before PROPOSED; actual conformance plus existing maintainer transition before EXPERIMENTAL snapshot. No new public language binding.',genericRationale:'Scoped attributable working text candidates and lexical retrieval are reusable across project workers/providers; no tenant names, MemoryV4 endpoints or SQLite representation in the contract.',proposer:'Hermes Phase5.1 implementation worker'};
checkDescriptor(canonical(descriptor));validateProposal(proposal);
for(const[name,data]of Object.entries({'descriptor.json':descriptor,'definition.json':definition,'namespace-policy.json':policy,'proposal.json':proposal}))writeFileSync(new URL(name,import.meta.url),JSON.stringify(data,null,2)+'\n');
validateDefinition(definition,localReader(new URL('.',import.meta.url).pathname),policy,{release:false});
console.log(JSON.stringify({status:'DRAFT_VALIDATED_NOT_REVIEWED_OR_ADMITTED',descriptorDigest:digest(descriptor),releaseEntries:0,ownerAcceptance:false}));
