// Generate private wire types and embedded schemas from the approved documents.
// No runtime reads of mutable schema paths and no public SDK exports.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const inputs = [
  'docs/g6/draft/frames.schema.json',
  'docs/g6/draft/context-offer.schema.json',
];
const documents = inputs.map((p) => JSON.parse(readFileSync(p, 'utf8')));
const external = new Map();
function name(s) {
  return s.replace(/[^a-zA-Z0-9]/g, '_');
}
function shape(s) {
  if (s === true) return 'unknown';
  if (s === false) return 'never';
  if (s.$ref) {
    if (s.$ref.startsWith('#/$defs/')) return name(s.$ref.slice(8));
    const [url, pointer] = s.$ref.split('#');
    const file = url.split('/').at(-1);
    const doc = JSON.parse(readFileSync('specs/schemas/' + file, 'utf8'));
    let target = doc;
    for (const k of (pointer || '').split('/').slice(1)) target = target[k];
    // External schemas may use local definitions of their own.
    const expand = (v) => {
      if (!v || typeof v !== 'object') return v;
      if (v.$ref?.startsWith('#/')) {
        let t = doc;
        for (const k of v.$ref.slice(2).split('/')) t = t[k];
        return expand(t);
      }
      return Array.isArray(v)
        ? v.map(expand)
        : Object.fromEntries(Object.entries(v).map(([k, x]) => [k, expand(x)]));
    };
    const id = 'external_' + name(file + (pointer || ''));
    if (!external.has(id)) external.set(id, shape(expand(target)));
    return id;
  }
  if ('const' in s) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(' | ');
  if (s.oneOf || s.anyOf)
    return '(' + (s.oneOf || s.anyOf).map(shape).join(' | ') + ')';
  if (s.allOf) return '(' + s.allOf.map(shape).join(' & ') + ')';
  if (s.type === 'array') return 'Array<' + shape(s.items || true) + '>';
  if (s.type === 'object' || s.properties) {
    const fields = Object.entries(s.properties || {}).map(
      ([k, v]) =>
        JSON.stringify(k) +
        (s.required?.includes(k) ? '' : '?') +
        ': ' +
        shape(v),
    );
    if (s.additionalProperties && typeof s.additionalProperties === 'object')
      fields.push('[key: string]: ' + shape(s.additionalProperties));
    return '{ ' + fields.join('; ') + ' }';
  }
  return (
    {
      string: 'string',
      integer: 'number',
      number: 'number',
      boolean: 'boolean',
      null: 'null',
    }[s.type] || 'unknown'
  );
}
const types = Object.entries(documents[0].$defs).map(
  ([k, v]) => 'export type ' + name(k) + ' = ' + shape(v) + ';',
);
const offer = 'export type ContextOffer = ' + shape(documents[1]) + ';';
const hash = createHash('sha256');
for (const p of inputs) hash.update(readFileSync(p));
let out =
  '// Generated by tools/generate-g6-wire.mjs; do not edit.\n// Approved schema SHA-256: ' +
  hash.digest('hex') +
  '\n';
for (const [k, v] of external)
  out += '// prettier-ignore\ntype ' + k + ' = ' + v + ';\n';
for (const t of [...types, offer]) out += '// prettier-ignore\n' + t + '\n';
for (let n = 0; n < documents.length; n++)
  out +=
    '// prettier-ignore\nexport const ' +
    ['frameSchema', 'offerSchema'][n] +
    ' = ' +
    JSON.stringify(documents[n]) +
    ';\n';
const target = 'packages/kernel/src/g6/wire-schema.ts';
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== out)
    throw new Error('G6 generated wire schema/types are stale');
  console.log('G6 private wire schema/type synchronization passed');
} else writeFileSync(target, out);
