// Generated from frozen G1 schemas. check-schema-sync verifies exact equality.
export const schemas = {
  signature: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/signature.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      algorithm: { const: 'ed25519' },
      keyId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      signature: {
        type: 'string',
        minLength: 1,
        maxLength: 88,
        pattern: '^[A-Za-z0-9+/]{86}==$',
      },
    },
    required: ['algorithm', 'keyId', 'signature'],
  },
  plugin: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/plugin.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.plugin/v1' },
      id: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      version: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
      },
      publisher: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      execution: { enum: ['inproc', 'ipc'] },
      entrypoint: {
        type: 'string',
        minLength: 1,
        maxLength: 512,
        pattern:
          '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
      },
      provides: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            capabilityId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            version: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
            descriptorDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
            descriptorPath: {
              type: 'string',
              minLength: 1,
              maxLength: 512,
              pattern:
                '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
            },
          },
          required: [
            'capabilityId',
            'version',
            'descriptorDigest',
            'descriptorPath',
          ],
        },
        minItems: 0,
        maxItems: 256,
      },
      requires: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            capabilityId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            major: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
            minMinor: {
              type: 'integer',
              minimum: 0,
              maximum: 9007199254740991,
            },
            operations: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^[a-z][A-Za-z0-9]*$',
              },
              minItems: 0,
              maxItems: 256,
              uniqueItems: true,
            },
            features: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
              },
              minItems: 0,
              maxItems: 256,
              uniqueItems: true,
            },
            maxMinor: {
              type: 'integer',
              minimum: 0,
              maximum: 9007199254740991,
            },
            optionalFeatures: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
              },
              minItems: 0,
              maxItems: 256,
              uniqueItems: true,
            },
          },
          required: [
            'capabilityId',
            'major',
            'minMinor',
            'operations',
            'features',
          ],
        },
        minItems: 0,
        maxItems: 256,
      },
      secretReferences: {
        type: 'array',
        items: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
        },
        minItems: 0,
        maxItems: 256,
        uniqueItems: true,
      },
      optionalRequires: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            capabilityId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            major: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
            minMinor: {
              type: 'integer',
              minimum: 0,
              maximum: 9007199254740991,
            },
            operations: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^[a-z][A-Za-z0-9]*$',
              },
              minItems: 0,
              maxItems: 256,
              uniqueItems: true,
            },
            features: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
              },
              minItems: 0,
              maxItems: 256,
              uniqueItems: true,
            },
            maxMinor: {
              type: 'integer',
              minimum: 0,
              maximum: 9007199254740991,
            },
            optionalFeatures: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
              },
              minItems: 0,
              maxItems: 256,
              uniqueItems: true,
            },
          },
          required: [
            'capabilityId',
            'major',
            'minMinor',
            'operations',
            'features',
          ],
        },
        minItems: 0,
        maxItems: 256,
      },
      publishedEvents: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            version: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
            descriptorDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
            descriptorPath: {
              type: 'string',
              minLength: 1,
              maxLength: 512,
              pattern:
                '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
            },
            eventType: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
          },
          required: [
            'eventType',
            'version',
            'descriptorDigest',
            'descriptorPath',
          ],
        },
        maxItems: 256,
      },
      subscribedEvents: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            version: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
            descriptorDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
            descriptorPath: {
              type: 'string',
              minLength: 1,
              maxLength: 512,
              pattern:
                '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
            },
            eventType: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
          },
          required: [
            'eventType',
            'version',
            'descriptorDigest',
            'descriptorPath',
          ],
        },
        maxItems: 256,
      },
    },
    required: [
      'schemaVersion',
      'id',
      'version',
      'publisher',
      'execution',
      'entrypoint',
      'provides',
      'requires',
      'secretReferences',
      'optionalRequires',
      'publishedEvents',
      'subscribedEvents',
    ],
  },
  'root-rotation': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/root-rotation.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.root-rotation/v1' },
      priorVersion: { type: 'integer', minimum: 1, maximum: 9007199254740991 },
      nextVersion: { type: 'integer', minimum: 2, maximum: 9007199254740991 },
      priorPolicyDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      nextPolicyDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      priorKeyId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      nextKeyId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
    },
    required: [
      'schemaVersion',
      'priorVersion',
      'nextVersion',
      'priorPolicyDigest',
      'nextPolicyDigest',
      'priorKeyId',
      'nextKeyId',
    ],
  },
  grant: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/grant.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'acap.grant/v1' },
      grantId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      principal: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      scope: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      capabilityId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      operations: {
        type: 'array',
        items: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^[a-z][A-Za-z0-9]*$',
        },
        minItems: 1,
        maxItems: 256,
        uniqueItems: true,
      },
      issuedAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      expiresAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      revision: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      instanceId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      scopeGeneration: {
        type: 'integer',
        minimum: 1,
        maximum: 9007199254740991,
      },
    },
    required: [
      'schemaVersion',
      'grantId',
      'principal',
      'scope',
      'capabilityId',
      'operations',
      'issuedAtMs',
      'expiresAtMs',
      'revision',
      'instanceId',
      'scopeGeneration',
    ],
  },
  capability: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/capability.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'acap.capability/v1' },
      id: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      version: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
      },
      features: {
        type: 'array',
        items: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
        },
        minItems: 0,
        maxItems: 256,
        uniqueItems: true,
      },
      operations: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            name: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][A-Za-z0-9]*$',
            },
            kind: { enum: ['unary', 'stream'] },
            input: { $ref: '#/$defs/payload' },
            output: { $ref: '#/$defs/payload' },
            idempotency: { enum: ['none', 'provider'] },
            idempotencyPolicy: {
              type: 'object',
              additionalProperties: false,
              properties: {
                retentionMs: {
                  type: 'integer',
                  minimum: 1,
                  maximum: 9007199254740991,
                },
                persistence: { enum: ['instance', 'durable'] },
              },
              required: ['retentionMs', 'persistence'],
            },
          },
          required: ['name', 'kind', 'input', 'output', 'idempotency'],
          allOf: [
            {
              if: { properties: { idempotency: { const: 'provider' } } },
              then: { required: ['idempotencyPolicy'] },
              else: { not: { required: ['idempotencyPolicy'] } },
            },
          ],
        },
        minItems: 1,
        maxItems: 256,
      },
    },
    required: ['schemaVersion', 'id', 'version', 'features', 'operations'],
    $defs: {
      payload: {
        type: 'object',
        additionalProperties: false,
        properties: {
          type: {
            enum: ['object', 'array', 'string', 'integer', 'boolean', 'null'],
          },
          properties: {
            type: 'object',
            propertyNames: { pattern: '^[A-Za-z_][A-Za-z0-9_]*$' },
            additionalProperties: { $ref: '#/$defs/payload' },
          },
          required: {
            type: 'array',
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[A-Za-z_][A-Za-z0-9_]*$',
            },
            minItems: 0,
            maxItems: 256,
            uniqueItems: true,
          },
          additionalProperties: { const: false },
          items: { $ref: '#/$defs/payload' },
          minItems: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          maxItems: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          minLength: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          maxLength: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          minimum: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991,
          },
          maximum: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991,
          },
          enum: { type: 'array', items: {}, minItems: 1, maxItems: 256 },
          const: {},
          description: { type: 'string', maxLength: 4096 },
        },
        required: ['type'],
        allOf: [
          {
            if: { properties: { type: { const: 'object' } } },
            then: { required: ['properties', 'additionalProperties'] },
          },
          {
            if: { properties: { type: { const: 'array' } } },
            then: { required: ['items'] },
          },
        ],
      },
    },
  },
  profile: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/profile.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.profile/v1' },
      profileId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      version: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
      },
      plugins: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            id: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            version: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
            packageDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
          },
          required: ['id', 'version', 'packageDigest'],
        },
        minItems: 1,
        maxItems: 256,
      },
      providerPins: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            capabilityId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            providerId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
          },
          required: ['capabilityId', 'providerId'],
        },
        minItems: 0,
        maxItems: 256,
      },
      scopes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            id: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
            },
            parent: {
              anyOf: [
                {
                  type: 'string',
                  minLength: 1,
                  maxLength: 128,
                  pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
                },
                { type: 'null' },
              ],
            },
          },
          required: ['id', 'parent'],
        },
        minItems: 1,
        maxItems: 256,
      },
    },
    required: [
      'schemaVersion',
      'profileId',
      'version',
      'plugins',
      'providerPins',
      'scopes',
    ],
  },
  error: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/error.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      code: {
        enum: [
          'INVALID_ARGUMENT',
          'UNAUTHENTICATED',
          'PERMISSION_DENIED',
          'NOT_FOUND',
          'INCOMPATIBLE_VERSION',
          'CONTRACT_MISMATCH',
          'CONFLICT',
          'DEADLINE_EXCEEDED',
          'CANCELLED',
          'UNAVAILABLE',
          'RESOURCE_EXHAUSTED',
          'FAILED_PRECONDITION',
          'INTERNAL',
        ],
      },
      message: { type: 'string', maxLength: 512 },
      retryable: { type: 'boolean' },
      correlationId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
    },
    required: ['code', 'message', 'retryable', 'correlationId'],
  },
  'event-descriptor': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/event-descriptor.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'acap.event-descriptor/v1' },
      id: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      version: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
      },
      payload: { $ref: '#/$defs/payload' },
    },
    required: ['schemaVersion', 'id', 'version', 'payload'],
    $defs: {
      payload: {
        type: 'object',
        additionalProperties: false,
        properties: {
          type: {
            enum: ['object', 'array', 'string', 'integer', 'boolean', 'null'],
          },
          properties: {
            type: 'object',
            propertyNames: { pattern: '^[A-Za-z_][A-Za-z0-9_]*$' },
            additionalProperties: { $ref: '#/$defs/payload' },
          },
          required: {
            type: 'array',
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[A-Za-z_][A-Za-z0-9_]*$',
            },
            minItems: 0,
            maxItems: 256,
            uniqueItems: true,
          },
          additionalProperties: { const: false },
          items: { $ref: '#/$defs/payload' },
          minItems: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          maxItems: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          minLength: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          maxLength: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
          minimum: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991,
          },
          maximum: {
            type: 'integer',
            minimum: -9007199254740991,
            maximum: 9007199254740991,
          },
          enum: { type: 'array', items: {}, minItems: 1, maxItems: 256 },
          const: {},
          description: { type: 'string', maxLength: 4096 },
        },
        required: ['type'],
        allOf: [
          {
            if: { properties: { type: { const: 'object' } } },
            then: { required: ['properties', 'additionalProperties'] },
          },
          {
            if: { properties: { type: { const: 'array' } } },
            then: { required: ['items'] },
          },
        ],
      },
    },
  },
  event: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/event.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      eventId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      type: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      contractDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      sourceProvider: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      sourceScope: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      sequence: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      timeMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      data: {},
      sourceInstanceId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      scopeGeneration: {
        type: 'integer',
        minimum: 1,
        maximum: 9007199254740991,
      },
    },
    required: [
      'eventId',
      'type',
      'contractDigest',
      'sourceProvider',
      'sourceScope',
      'sequence',
      'timeMs',
      'data',
      'sourceInstanceId',
      'scopeGeneration',
    ],
  },
  'package-index': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/package-index.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.package-index/v1' },
      pluginId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      version: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
      },
      manifestPath: {
        type: 'string',
        minLength: 1,
        maxLength: 512,
        pattern:
          '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
      },
      files: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            path: {
              type: 'string',
              minLength: 1,
              maxLength: 512,
              pattern:
                '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
            },
            bytes: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
            digest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
          },
          required: ['path', 'bytes', 'digest'],
        },
        minItems: 1,
        maxItems: 4096,
      },
    },
    required: ['schemaVersion', 'pluginId', 'version', 'manifestPath', 'files'],
  },
  response: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/response.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      requestId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      result: {
        oneOf: [
          {
            type: 'object',
            additionalProperties: false,
            properties: { kind: { const: 'success' }, value: {} },
            required: ['kind', 'value'],
          },
          {
            type: 'object',
            additionalProperties: false,
            properties: {
              kind: { const: 'error' },
              error: {
                type: 'object',
                additionalProperties: false,
                properties: {
                  code: {
                    enum: [
                      'INVALID_ARGUMENT',
                      'UNAUTHENTICATED',
                      'PERMISSION_DENIED',
                      'NOT_FOUND',
                      'INCOMPATIBLE_VERSION',
                      'CONTRACT_MISMATCH',
                      'CONFLICT',
                      'DEADLINE_EXCEEDED',
                      'CANCELLED',
                      'UNAVAILABLE',
                      'RESOURCE_EXHAUSTED',
                      'FAILED_PRECONDITION',
                      'INTERNAL',
                    ],
                  },
                  message: { type: 'string', maxLength: 512 },
                  retryable: { type: 'boolean' },
                  correlationId: {
                    type: 'string',
                    minLength: 1,
                    maxLength: 128,
                    pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
                  },
                },
                required: ['code', 'message', 'retryable', 'correlationId'],
              },
            },
            required: ['kind', 'error'],
          },
        ],
      },
    },
    required: ['requestId', 'result'],
  },
  'resolution-lock': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/resolution-lock.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.resolution-lock/v1' },
      profileDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      policyDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      plugins: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            id: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            version: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
            packageDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
          },
          required: ['id', 'version', 'packageDigest'],
        },
        maxItems: 256,
      },
      bindings: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            consumerId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            scope: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
            },
            capabilityId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            providerId: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            version: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
            descriptorDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
            packageDigest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
            providerVersion: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$',
            },
          },
          required: [
            'consumerId',
            'scope',
            'capabilityId',
            'providerId',
            'version',
            'descriptorDigest',
            'packageDigest',
            'providerVersion',
          ],
        },
        maxItems: 256,
      },
    },
    required: [
      'schemaVersion',
      'profileDigest',
      'policyDigest',
      'plugins',
      'bindings',
    ],
  },
  bundle: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/bundle.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.bundle/v1' },
      bundleId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      profileDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      artifacts: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            path: {
              type: 'string',
              minLength: 1,
              maxLength: 512,
              pattern:
                '^[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*(?:/[A-Za-z0-9_-]+(?:\\.[A-Za-z0-9_-]+)*)*$',
            },
            digest: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^sha256:[0-9a-f]{64}$',
            },
            bytes: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
            kind: {
              enum: [
                'runtime',
                'plugin',
                'descriptor',
                'manifest',
                'profile',
                'sbom',
                'provenance',
                'documentation',
              ],
            },
          },
          required: ['path', 'digest', 'bytes', 'kind'],
        },
        minItems: 1,
        maxItems: 4096,
      },
    },
    required: ['schemaVersion', 'bundleId', 'profileDigest', 'artifacts'],
  },
  'event-grant': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/event-grant.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'acap.event-grant/v1' },
      grantId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      principal: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      scope: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      issuedAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      expiresAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      revision: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      instanceId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      scopeGeneration: {
        type: 'integer',
        minimum: 1,
        maximum: 9007199254740991,
      },
      eventType: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      operations: {
        type: 'array',
        items: { enum: ['publish', 'subscribe'] },
        minItems: 1,
        maxItems: 2,
        uniqueItems: true,
      },
    },
    required: [
      'schemaVersion',
      'grantId',
      'principal',
      'scope',
      'issuedAtMs',
      'expiresAtMs',
      'revision',
      'instanceId',
      'scopeGeneration',
      'eventType',
      'operations',
    ],
  },
  'secret-grant': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/secret-grant.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'acap.secret-grant/v1' },
      grantId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      principal: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      scope: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      issuedAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      expiresAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      revision: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      instanceId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      scopeGeneration: {
        type: 'integer',
        minimum: 1,
        maximum: 9007199254740991,
      },
      secretRef: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      operations: {
        type: 'array',
        items: { const: 'read' },
        minItems: 1,
        maxItems: 1,
        uniqueItems: true,
      },
    },
    required: [
      'schemaVersion',
      'grantId',
      'principal',
      'scope',
      'issuedAtMs',
      'expiresAtMs',
      'revision',
      'instanceId',
      'scopeGeneration',
      'secretRef',
      'operations',
    ],
  },
  revocation: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/revocation.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.revocation/v1' },
      version: { type: 'integer', minimum: 1, maximum: 9007199254740991 },
      issuedAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      expiresAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      revokedKeyIds: {
        type: 'array',
        items: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^sha256:[0-9a-f]{64}$',
        },
        minItems: 0,
        maxItems: 256,
        uniqueItems: true,
      },
      revokedArtifactDigests: {
        type: 'array',
        items: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^sha256:[0-9a-f]{64}$',
        },
        minItems: 0,
        maxItems: 256,
        uniqueItems: true,
      },
    },
    required: [
      'schemaVersion',
      'version',
      'issuedAtMs',
      'expiresAtMs',
      'revokedKeyIds',
      'revokedArtifactDigests',
    ],
  },
  'trust-policy': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/trust-policy.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      schemaVersion: { const: 'alica.trust-policy/v1' },
      version: { type: 'integer', minimum: 1, maximum: 9007199254740991 },
      rootKeyIds: {
        type: 'array',
        items: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^sha256:[0-9a-f]{64}$',
        },
        minItems: 1,
        maxItems: 1,
        uniqueItems: true,
      },
      publishers: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            id: {
              type: 'string',
              minLength: 1,
              maxLength: 128,
              pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
            },
            keyIds: {
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 128,
                pattern: '^sha256:[0-9a-f]{64}$',
              },
              minItems: 1,
              maxItems: 256,
              uniqueItems: true,
            },
            executionModes: {
              type: 'array',
              items: { enum: ['inproc', 'ipc'] },
              minItems: 1,
              maxItems: 2,
              uniqueItems: true,
            },
          },
          required: ['id', 'keyIds', 'executionModes'],
        },
        minItems: 1,
        maxItems: 256,
      },
      expiresAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      maxOfflineAgeMs: {
        type: 'integer',
        minimum: 0,
        maximum: 9007199254740991,
      },
      issuedAtMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
    },
    required: [
      'schemaVersion',
      'version',
      'rootKeyIds',
      'publishers',
      'expiresAtMs',
      'maxOfflineAgeMs',
      'issuedAtMs',
    ],
  },
  call: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://alica.invalid/specs/call.schema.json',
    type: 'object',
    additionalProperties: false,
    properties: {
      requestId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
      capabilityId: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$',
      },
      descriptorDigest: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^sha256:[0-9a-f]{64}$',
      },
      operation: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[a-z][A-Za-z0-9]*$',
      },
      deadlineMs: { type: 'integer', minimum: 0, maximum: 9007199254740991 },
      payload: {},
      idempotencyKey: {
        type: 'string',
        minLength: 1,
        maxLength: 128,
        pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$',
      },
    },
    required: [
      'requestId',
      'capabilityId',
      'descriptorDigest',
      'operation',
      'deadlineMs',
      'payload',
    ],
  },
};
